services:
  db:
    build: ./Database
    ports:
      - "27017:27017"
    volumes:
      - link-vault-data:/data/db

  api:
    build: ./link-vault-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  frontend:
    build:
      context: ./link-vault-frontend/frontend
      args:
        VITE_API_URL: http://api:5000
    ports:
      - "3000:80"
    depends_on:
      - api
volumes:
  link-vault-data: